### PR TITLE
[WIP] Standardize on Julia 1.6.2

### LINKED ISSUE #125: Buildkite CI broken on staging branch
**Issue:**
[CI](https://buildkite.com/clima/calibrateemulatesample-ci/builds/50#8fda231f-52ab-47d7-89a6-6c0f7ed7e738) for PR #120 (`staging` branch) fails in the `init_project_env` setup stage. The error happens in `Pkg.instantiate()`, before Python dependencies are added:

```
Added registry `General` to `/central/scratch/climaci/calibrateemulatesample-ci/50/depot/cpu/registries/General`
--
  | Cloning git-repo `https://github.com/CliMA/EnsembleKalmanProcesses.jl`
  | ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec
  | Stacktrace:
  | [1] load_urls(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:510
  | [2] #download_source#54 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:686 [inlined]
  | [3] download_source at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:685 [inlined]
  | [4] instantiate(::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:875
  | [5] #instantiate#169 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:791 [inlined]
  | [6] top-level scope at none:1
  | 🚨 Error: The command exited with status 1
```

**Diagnosis:**
Googling the error message suggests this is caused by using a `Manifest.toml` from an incompatible version of Julia (differing minor version number): [ref 1](https://discourse.julialang.org/t/incompatible-changes-in-pkg/51326/5); [ref 2](https://github.com/tlienart/Franklin.jl/issues/868). 

This was introduced in 7f038a471fd55d61ddd9e9e880ae4203303de68c, which updates `Manifest.toml` to package versions apparently consistent with Julia 1.6.2, while the buildkite config is still using 1.5.4. 

**Proposed fix:**
Full reproducibility is, implicitly, a requirement of the CES project, so `Manifest.toml` must remain [tracked in the repo](https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029). This means the project must standardize on one minor version of Julia. I'm ignorant of whether there's a CliMA-wide policy on this, but the [current long-term support release](https://discourse.julialang.org/t/julia-v1-7-0-has-been-released-and-v1-6-is-now-lts/72336) is 1.6.5, which would imply updating buildkite and all tests to 1.6.

### PR DESCRIPTION
**Pull request by tsj5**
This is a revision of PR #126, which ran into a new problem (missing environment module) when attempting to fix #125 (Manifest.toml incompatibility between julia 1.5 and 1.6). See [most recent comment](https://github.com/CliMA/CalibrateEmulateSample.jl/pull/126#issuecomment-1015083815) on that PR.

Current PR pins the buildkite julia version at 1.6.2, for which a module currently exists. 

The `Manifest`s in this PR were generated under 1.6.5, and I haven't been able to verify that they're compatible with 1.6.2 (julialang.org didn't retain 1.6.2, and the conda package for 1.6.2 appears to be broken on osx).

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
it seems like the examples are broken?

**Comment by tsj5** [comment]
> it seems like the examples are broken?

Yeah, that's what I've got at this point: this PR is up-to-date with `staging`, which includes the merge from PR #120. That PR implemented major interface changes, e.g. replacing `GaussianProcessEmulator` with `Emulator.GaussianProcess`, but I'm still seeing references to the former class in the examples.

For what it's worth, unit tests pass on `staging` and on this PR.

File: examples/Lorenz/Lorenz_example.jl [hunk 1]
```diff
@@ -297,36 +302,34 @@ println(norm_factor)
...
     println(vec(y_mean))
     println(" GP variance")
     println(diag(y_var[1],0))
     println("true data: ")
-    if standardize
-        println(truth.mean ./ norm_factor)
-    else
-        println(truth.mean)
-    end
+    println(truth.mean) # same, regardless of norm_factor
```
Comment (tsj5) [inline examples/Lorenz/Lorenz_example.jl:332]: We shouldn't have needed to rescale `truth.mean`, since that's what the emulator is emulating, and in the new code `y_mean` is correctly scaled by `reverse_standardize`. Verified that `vec(y_mean) ≈ truth.mean` in the new code, which means this was being done incorrectly (but consistently) on the existing code in `/master`.

**Comment by tsj5** [comment]
Output of examples now either reproduce `/master` exactly, or correct known issues in `/master` (thanks to @odunbar for help in debugging). All unit tests and examples now run on julia 1.6.5 (can't get an instance of 1.6.2 running locally). 

@jakebolewski, we're ready to rerun buildkite when you get a sec. Thanks!

**Comment by tsj5** [comment]
> need to reflect the new example path (also for the artifacts)

Agh, can't believe I missed that! Thanks for catching that mistake, @jakebolewski !

**Comment by jakebolewski** [comment]
It looks like the load path needs to be adjusted in the buildkite file

**Comment by tsj5** [comment]
Thanks again @jakebolewski -- this is fixed in new PR #128, since I can't re-open this one. 

Verified that the GaussianProcess examples now run when the exact commands in pipeline.yml are invoked from the repo dir (previously was running from the examples' directory, with the CES module previously loaded in the REPL, which I'm guessing is why I didn't hit the error earlier.)
